[[redirects]]
  from = "/"
  to = "https://mirela-cv.netlify.app/"
  status = 301

[[redirects]]
  from = "/*"
  to = "https://mirela-cv.netlify.app/:splat"
  status = 301

[[redirects]]
  from = "/Projects/*"
  to = "https://cs-projects.netlify.app/:splat"
  status = 301

[[redirects]]
  from = "/schety"
  to = "https://mirela-cv.netlify.app/schety"
  status = 301
